### ISSUE TITLE
Did you miss dropout?

### ISSUE THREAD

**Issue by Fei-Wang** [lucidrains/vit-pytorch#209]
https://github.com/lucidrains/vit-pytorch/blob/6d7298d8ad5b15510f49b977847a3364302e74d2/vit_pytorch/vit.py#L58

Whether or not should add dropout layer after attention?

**Comment by lucidrains** [comment]
@Fei-Wang Hi Fei, so it turns out I removed the post-attention dropout due to an earlier issue https://github.com/lucidrains/vit-pytorch/pull/7 I must have read it too fast and concluded too soon that ViT did not have that specific dropout, when in fact, now that I look back on the original Jax repository, they do include that dropout..

I've readded that dropout throughout the entire repository, do let me know if I missed any!

**Comment by lucidrains** [comment]
https://github.com/lucidrains/vit-pytorch/pull/7/files#diff-fce7f92e0b957764a240f657482514430a2fcdd8a0fcfc1d23372f119a92e6ccL57
