### ISSUE TITLE
Layernorm in Cross attention

### ISSUE THREAD

**Issue by turtleman99** [lucidrains/vit-pytorch#287]
I'm wondering why we don't need `layernorm` for K and V, but need it for Q in cross attention. Is there any paper I can refer to? Thanks a lot.

https://github.com/lucidrains/vit-pytorch/blob/0ad09c4cbc57af3c8bb404fda36a47a7bee66ece/vit_pytorch/cross_vit.py#L53-L71

**Comment by lucidrains** [comment]
it has been a while, but can you check to see if the context being received isn't coming from another transformer with a final layernorm?

**Comment by turtleman99** [comment]
oh, this is a good point. My `x` and `context` are actually features from pre-trained ViT models. I believe I can remove `layernorm` for `x` and `context`, right?

**Comment by lucidrains** [comment]
@turtleman99 if you are following the same scheme as cross vit, then the code is correct and stays the same. `x` is layernorm (pre-layernorm configuration + residual), while `context` is left alone since it is already layernorm-ed. You would only need to layernorm the context if the context also evolves along with `x`, like in the [ISAB](https://github.com/lucidrains/isab-pytorch) architecture

**Comment by turtleman99** [comment]
Gotcha. Thank you so much for your explanations! :)
